version: 0.2
phases:
  install:
    runtime-versions:
     dotnet: 2.2
  build:
    commands:
      - dotnet test ./dotnet-core-tutorial.csproj
      - dotnet publish -c release -o ./build_output ./dotnet-core-tutorial.csproj
artifacts:
  files:
    - test/*
    - appspec.yml
