version: 0.2
phases:
  install:
    runtime-versions:
     dotnet: 2.2
  build:
    commands:
      - dotnet test ./src/awspipline/dotnet-core-tutorial.csproj
      - dotnet publish -c release -o ./build_output ./src/awspipline/dotnet-core-tutorial.csproj
artifacts:
  files:
    - src/HelloWorldWebCore/build_output/*
